<?php
require_once 'fragment.php';
$f = start('fr');
?>
<div class="cols">
    <p>J'ai toujours trouvé que dans <?= $f->def('cities-skylines') ?>, les villes ont un look international plutôt fade et homogène. Où sont le goût, l'émotion, la particularité, toutes ces choses qui font le charme d'une ville&nbsp;? Alors j'ai essayé de reproduire des villes et villages européens, notamment français. Et c'est ce qui a créé le besoin pour une route française, qui respecte les normes réelles pour le marquage au sol et les panneaux. Personne ne l'avait encore fait sur le Workshop, alors je m'y suis mis. J'ai ainsi découvert les bases du texturing et de la modélisation 3D.</p>
    <p>Mettre un pied dans le monde de la modélisation 3D et du game design aura été une expérience enrichissante pour moi, même si je n'en ferai pas une passion.</p>
</div>