<?php
require_once 'fragment.php';
$f = new Fragment(__FILE__, 'en') ?>
<p>The goal of this project was to create a functional Sudoku game in the <?= $f->def('c') ?> language, playable via the Linux terminal.</p>
<blockquote>
    <p>The association <q>Les têtes à clic</q> works in middle schools to familiarize students with the use of software. It also develops small computer board games for children. As an intern in this association, you are responsible for developing a program that allows a middle school student to fill in a Sudoku grid.</p>
    <footer>— <cite>Project topic</cite></footer>
</blockquote>