<?php
require_once 'fragment.php';
$f = new Fragment(__FILE__, 'fr') ?>
<p>Les îles dans le <?= $f->def('anno2070') ?> ne sont pas générées aléatoirement. Il y un ensemble d'îles prédéfinies dans les fichiers du jeu. Elles sont pivotées et placées aléatoirement pour rendre chaque carte unique, mais toutes les cartes dans <?= $f->def('anno2070') ?> ont en réalité les mêmes îles.</p>
<p>Je les ai donc reproduites dans <?= $f->def('anno-designer') ?>.</p>
<article>
    <h3>Utilisations possibles</h3>
    <ul class="list">
        <li>
            <p><strong>Computing optimal island-wide layouts with an algorithm</strong> (really looking forward to that one).</p>
        </li>
        <li>
            <p><strong>Créer des plans à l'échelle d'une île.</strong> J'utilise souvent des plans de construction pour optimiser l'utilisation de l'espace, mais les plans ont un défaut majeur&nbsp;: on suppose qu'ils sont rectangulaires. Leur efficacité spatiale est basée sur leur cadre englobant, mais les îles ne sont pas des rectangles. Elles prennent des formes plutôt irrégulières. C'est pourquoi on ne peut pas se fier uniquement aux plans de construction actuels pour construire efficacement.</p>
        </li>
        <li>
            <p><strong>Calculer des plans optimaux à l'échelle d'une île avec un algorithme</strong> (j'attends vraiment celui-là avec impatience). C'est un problème NP-difficile<?=$f->ref()?>, donc la solution nécessitera l'utilisation d'heuristiques. Je n'ai pas encore cherché très profondément, mais l'implémentation promet d'être un défi intéressant.</p>
        </li>
    </ul>
    <ul class="list">
        <li>
            <p><strong>Noir</strong>&nbsp;: tuile bloquée (rocher, récif, rivière&hellip;)</p>
        </li>
        <li>
            <p><strong>Jaune</strong>&nbsp;: rive (près des rivières et sur la côte, certaines tuiles peuvent avoir des routes construites dessus, mais rien d'autre)</p>
        </li>
        <li>
            <p><strong>Vide</strong>&nbsp;: eau ou terre.</p>
        </li>
        <li>
            <p><strong>Violet</strong>&nbsp;: bizarrerie (tuiles au comportement étrange)</p>
        </li>
    </ul>
    <figure class="figure">
        <img src="/portfolio/img/projects/island-maps/3_mines_1_river.webp" alt="Île 1 &ndash; 3 mines, 1 emplacement fluvial" width="800" height="571" loading="lazy" title="Island 1 &ndash; 3 mines, 1 emplacement fluival">
        <figcaption>Island 1 &ndash; 3 mines, 1 emplacement fluival</figcaption>
    </figure>
    <p>C'est la première île que j'ai reproduite. Elle fait partie des plus petites îles du jeu.</p>
    <p><strong>Bizarrerie</strong>: celle cellule n'est pas constructible, mais il ya quand même un son quand on tente de construire une route dessus.</p>
</article>