<?php
require_once 'fragment.php';
$f = start('en');
?>
<div>
    <p>The goal of this project was to create a <? $f->def('php') ?> document generator using Docker containerization and also using <?= $f->def('php') ?>, scripting <?= $f->def('bash') ?> etc. We were in groups of 4. On my side, I took care of writing a Markdown parser in <? $f->def('php') ?>. Our teachers were smart: they modified the Markdown syntax so that we could not simply copy a parser from the Internet.</p>
</div>