<?php
require_once 'fragment.php';
$f = new Fragment(__FILE__, 'en')
?>
<p>Hello, my name is <strong>Raphaël Bardini</strong>. I'm an 18 y/o computer science student in second year of <abbr title="Bachelor of Technology">BUT</abbr> Informatique, at the <?= $f->blank('<abbr title="University Technological Institute">IUT</abbr> of Lannion', 'https://iut-lannion.univ-rennes.fr/') ?></a>.</p>
<p>In 2023, I passed my baccalaureate with the specialties <?= $f->def('amc') ?> et <?= $f->def('nsi') ?>.</p>
<p>The main source of fulfilment in my life is <strong>software development</strong>. In addition, I commit <em>(pun intented)</em> to the <strong>open-source</strong> community. And I can't deny that I'm a big lover of <?= $f->blank('jazz music', 'https://youtube.com/playlist?list=PL1weKnP9ENMdJbMr338lNOMSF487f8nGm') ?>. Join me in this adventure&nbsp;! &#9749;</p>