<p>Étant enfant mes parents m'ont fait découvrir Val d'Isère, une station de ski située dans les Alpes. Depuis, nous y retournons deux fois par an, en été et en hiver.</p>
<figure class="figure">
    <p>(comparaison photo été/hiver slider (vue depuis appart))</p>
    <figcaption>vue depuis notre appartement été/hiver</figcaption>
</figure>
<h4>L'hiver</h4>
<p>En hiver, nous faisons principalement du ski. Le domaine skiable est le plus grand d'Europe, et donc même après toute ces années, nous n'avons pas encore été partout.</p>
<figure class="figure">
    <p>(photo ski télésiège brouillard)</p>
    <figcaption>on y voit rien!</figcaption>
</figure>
<p>Je suis passé par l'`<abbr title="École de ski français">ESF</abbr>`. Cependant après avoir obtenu l'Étoile d'Or, j'ai décidé de ne pas continuer en compétition car ce n'est pas vraiment mon état d'esprit. Étant en vacances, je viens skier pour me détendre et rester tranquille. Cependant ça ne veut pas dire que je ne prends pas plaisir à relever certains défis&nbsp;:</p>
<p>Chaque année nous tentons d'en profiter le plus possible, car à cause du réchauffement climatique, les glaciers reculent et les couches de neiges s'amincissent chaque année un peu plus.</p>
<p>Tôt ou tard, le ski disparaitera. Val d'Isère, une des plus hautes stations de France, sera le dernier bastion de ce sport mythique. Du moins jusqu'à ce que le réchauffement ne l'atteigne elle aussi.</p>
<p>Ce n'est pas si grave, il restera toujours les activités estivales.</p>
<h4>L'été</h4>
<p>L'été, nous faisons surtout de la randonnée. Il y a énormément de sentiers accessibles aux piétons dans les environs. Cependant les meilleures vues ne se trouvent pas toujours sur les chemins les plus fréquentés&nbsp;:</p>
<figure class="figure">
    <p>(pissaillas glacier)</p>
    <figcaption>Nous avons grimpé jusqu'au glacier du Pissaillas depuis le col de l'Iseran. Nous étions seuls et le paysage était simplement merveilleux.</figcaption>
</figure>