<?php
require 'fragment.php';
define('LANG', 'fr');
?>
<p>Avez-vous déjà entendu parler de SurvivalWorld<?php reference() ?>, ou Dreamfinity<?php reference() ?>&nbsp;? Ils ont une chose en commun&nbsp;: ce sont des serveurs <?php definition(LANG, 'minecraft') ?> orientés survie, ou les joueurs sont libres de construire ce qu'il veulent, d'amasser des richesses et d'échanger avec les autres joueurs dans une économie simulée.</p>
<h4>SurvivalWorld</h4>
<figure>
    <p>(screen survivalworld)</p>
    <figcaption>Ma base sur SurvivalWorld</figcaption>
</figure>
<p>Le serveur de survive francophone mythique. Il a traversé les versions du jeu. Ouvert en 2016, je ne l'ai rejoint qu'en 2019. Bien que je sois inactif depuis mon entrée en BUT Informatique, j'aurai passé d'excellents moments avec sa communauté accueillante.</p>
<p>Avec la pléthore de temps libre que m'a donné le confinement en 2020, j'ai bâti un empire commercial. Je suis devenu un des plus riches joueurs du serveur.</p>
<figure>
    <p>(screen nether quartz tower)</p>
    <figcaption>Et oui, j'avais pas mal de temps libre.</figcaption>
</figure>
<p>J'ai bâti et perdu des amitiés. J'ai exploré, construit, colonisé, exploité, automatisé, et amassé de nombreuses richesses à travers ce monde fictif.</p>
<p>Cependant, avec le temps je me suis progressivement lassé du jeu et j'ai choisi de faire don de toutes mes possessions à un ami.</p>
<p>Mais bon, peut-être qu'un de ces jours je reviendrai y faire un tour.</p>
<h4>Dreamfinity</h4>
<p><?php definition(LANG, 'minecraft') ?> est un jeu très complet, mais j'ai toujours eu un intérêt pour les mods. En particuler par rapport à l'industrialisation et l'automatisation.</p>
<p>Car oui, dans les jeux-vidéos ce qui me plaît le plus c'est exploiter l'environnement, construire des usines, automatiser la production. Mieux vaut faire cela dans un jeu-vidéo que dans la vraie vie.</p>
<p>Pour cela il faut des mods comme BuildCraft<?php reference() ?>, IndustrialCraft<?php reference() ?>, GalactiCraft<?php reference() ?>, Immersive Engineering<?php reference() ?>&hellip; J'avais déjà fait de nombreuses parties en solo mais j'en étais lassé. Je voulais goûter à l'expérience en multijoueur.</p>
<p>C'est pour ça que j'ai choisi de rejoindre <?php definition(LANG, 'dreamfinity') ?>, un serveur survie/faction sur ce même thème de l'automatisation.</p>
<p>J'ai commencé sur Spacecross. J'ai parcouru le monde pendant un temps avant de poser mes valises dans steppe, entre 3 collines.</p>
<h5>Ma (brève) conquête spatiale</h5>
<p>La conquête de la Lune aura été un passage court mais intense de ma partie.</p>
<p>Après avoir construit une fusée, je m'élance vers les cieux.</p>
<p>(moi dans la fusée)</p>
<p>Cependant après être arrivé je m'aperçois d'un problème avec mon masque à oxygène et je commence à asphyxier&nbsp;:</p>
<p>(je m'asphyxie)</p>
<p>Heureusement, la cavalerie arrive&nbsp;: un autre joueur vole à mon secours.</p>
<p>(autre joueur vole à mon secours)</p>
<p>En dépit de la barrière de langue, nous sommes devenus amis.</p>
<p>Finalement, j'ai pu planter mon drapeau (qui n'a `<em>absolument</em>` aucun rapport avec l'actualité)</p>
<p>(screen selfie drapeau ukraine)</p>
<p>Au final, je suis surpris d'être arrivé si loin. Même si au final, ma base a été pillée et j'ai tout perdu, je me suis bien amusé à la construire.</p>
<p>De plus, je ne comprenais absolument rien au fonctionnement du serveur ou au messages. C'est un serveur russe et il n'y avait pas de traduction en anglais disponible.</p>
<h5>Technocracie et la grande réinitialisation</h5>
<p>Bon. Quelques mois après cette expériences assez frustrante j'ai rejoint Technocracy. Ce sous-serveur est similaire à Spacecross, à la différence qu'il n'est pas orienté vers la conquête spatiale mais l'industrialisation sur Terre. Ce qui est, au final, ce que je voulais. Et donc un système de claim est proposé pour protéger ses constructions des pillages.</p>
<p>J'ai construit ma base&nbsp;:</p>
<figure>
    <p>(screen de ma base)</p>
    <figcaption>Capture d'écran de ma base sur Technocracy. Un silo qui s'enfonçe sous terre avec un dôme en verre et une flèche symbolisant la puissance et la gloire de mon empire industriel.</figcaption>
</figure>
<p>Tout allait bien, cependant après une pose de quelques mois c'est l'effarement. Toutes mes ressources et constructions ont disparu.</p>
<p>Après avoir posé la question sur le serveur Discord Dreamfinity, j'apprends que le monde a été `<strong>réinitialisé</strong>`.</p>
<p>Autant dire que je ne reviendrais pas de sitôt sur ce serveur.</p>
<p>J'imagine que la leçon ici est que le solo, ce n'est pas si mal.</p>