<?php
require_once 'fragment.php';
$f = new Fragment(__FILE__, 'fr')
?>
J'ai été scolarisé au <?=$f->a('Lycée Saint-Joseph-Bossuet', 'https://www.saintjosephlannion.fr/')?> à Lannion. J'ai suivi la filère générale. En première, je suivis les spécialités <?=$f->def('spe-math')?>, <?=$f->def('nsi')?> et <?=$f->def('amc')?>. En terminale, je décide d'abandonner les mathématiques au profit de mes deux autres spécialités. Au baccalauréat, j'ai eu la mention Bien.