<?php
require_once 'fragment.php';
$f = start('en') ?>
<div>
    <p>Have you ever heard of <?= $f->def('survivalworld') ?>, or <?= $f->def('dreamfinity') ?>? They have one thing in common: they are survival-oriented <?= $f->def('minecraft') ?> servers, where players are free to build whatever they want, amass wealth, and trade with other players in a simulated economy.</p>
</div>
<article>
    <h3>SurvivalWorld</h3>
    <div>
        <figure class="figure">
            <p>(screen survivalworld)</p>
            <figcaption>My base on SurvivalWorld</figcaption>
        </figure>
        <p>The legendary French-speaking survival server. It has spanned the game's versions. Opened in <?= $f->year(2016) ?>, I only joined in <?= $f->year(2019) ?>. Although I have been inactive since joining BUT Informatique, I have had great times with its welcoming community.</p>
        <p>With the plethora of free time that confinement gave me in 2020, I built a business empire. I became one of the richest players on the server.</p>
        <figure class="figure">
            <p>(screen nether quartz tower)</p>
            <figcaption>And yes, I had a lot of free time.</figcaption>
        </figure>
        <p>I have built and lost friendships. I explored, built, colonized, exploited, automated, and amassed a lot of wealth throughout this fictional world.</p>
        <p>However, over time I gradually grew tired of the game and chose to donate all my possessions to a friend.</p>
        <p>But hey, maybe one of these days I'll come back and have a look.</p>
    </div>
</article>
<article>
    <h3>Dreamfinity</h3>
    <div>
        <p><?= $f->def('minecraft') ?> is a very complete game, but I've always had an interest in mods. Especially in relation to industrialization and automation.</p>
        <p>Because yes, in video games what I like the most is exploiting the environment, building factories, automating production. It's better to do this in a video game than in real life.</p>
        <p>For this you need mods like <?= $f->def('buildcraft') ?>, <?= $f->def('industrialcraft-2') ?>, <?= $f->def('galacticraft') ?>, <?= $f->def('immersive-engineering') ?>... I had already played many solo games but I was tired of them. I wanted to try the multiplayer experience.</p>
        <p>That's why I chose to join <?= $f->def('dreamfinity') ?>, a survival/faction server on the same theme of automation.</p>
        <p>I started on Spacecross. I traveled the world for a while before settling down in the steppe, between 3 hills.</p>
        <h4>My (brief) space conquest</h4>
        <p>The conquest of the Moon was a short but intense part of my game.</p>
        <p>After building a rocket, I launched into the skies.</p>
        <p>(me in the rocket)</p>
        <p>However, after arriving, I noticed a problem with my oxygen mask and I began to suffocate:</p>
        <p>(I am suffocating)</p>
        <p>Fortunately, the cavalry arrived: another player came to my rescue.</p>
        <p>(another player came to my rescue)</p>
        <p>Despite the language barrier, we became friends.</p>
        <p>Finally, I was able to plant my flag (which has <em>absolutely</em> nothing to do with current events)</p>
        <p>(screen selfie ukraine flag)</p>
        <p>In the end, I'm surprised to have made it this far. Even though in the end, my base was looted and I lost everything, I had a lot of fun building it.</p>
        <p>Also, I didn't understand anything about how the server worked or the messages. It's a Russian server and there was no English translation available.</p>
        <h4>Technocracy and the Great Reset</h4>
        <p>Okay. A few months after this rather frustrating experience I joined Technocracy. This sub-server is similar to Spacecross, except that it is not oriented towards space conquest but industrialization on Earth. Which is, in the end, what I wanted. And so a claim system is proposed to protect its constructions from looting.</p>
        <p>I built my base:</p>
        <figure class="figure">
            <p>(screenshot of my base)</p>
            <figcaption>Screenshot of my base on Technocracy. A silo that sinks underground with a glass dome and a spire symbolizing the power and glory of my industrial empire.</figcaption>
        </figure>
        <p>Everything was fine, however after a few months of rest it was dismay. All my resources and constructions disappeared.</p>
        <p>After asking the question on the Dreamfinity Discord server, I learned that the world had been <strong>reset</strong>.</p>
        <p>Suffice to say, I won't be returning to this server anytime soon.</p>
        <p>I guess the lesson here is that solo isn't so bad.</p>
    </div>
</article>