<?php
require_once 'fragment.php';
$f = new Fragment(__FILE__, 'en') ?>
<div>
    <h3>Prologue &mdash; The Evening</h3>
    <p>On a Friday eveneing, in the home of the Martinaches, safely isolated from the freezing cold of the barren nights of late winter, Emmanuel and his wife are watching TV news.</p>
    <p><q>Thee whereabouts of Vladimir Putin are currrently unknown&hellip;</q></p>
    <p>Emmanuel mechanically changes the channel.</p>
    <p><q>Several major political figured seem to have disappeared, with little to no explanation from governments. Subsitute UN secretary-</q></p>
    <p>Suddenly, the screen goes black, cutting the reporter.</p>
    <p>The couple looks at the TV screen in disbelief, until a bright display came up, reading <q>Emergency alert - Please stand by until further notice</q>. The words <q>This is not a test</q> are flashing in red near the bottom of the screen.</p>
    <p>Moments later, viewers across all continents were greeted with a alert about an oncoming nuclear attack. They were briefed about the threat, given rudimentary safety instructions, and urged not to leave home.</p>
    <p>All across the world, phones were vibrating, alarms were ringing, all devices were repeating this same message.</p>
    <p>The world was hung.</p>
    <p>Emmanuel's family quickly gathered in their basement. They had supplies down there, and according to the government safety recommendations, it was the safest place where they could be.</p>
    <p>Emmanuel held tightly for what seemed to be hours, deadly silece sometimes troubled by sounds of roofs cracking open and trees falling down.</p>
    <p>He was scared, but he was alive.</p>
    <h3>Chapter 1: Pitch-black</h3>
    <h4>May <?= $f->year(2034) ?></h4>
    <h5>Tuesday</h5>
    <p>11 years ago, there was a nuclear war. No one remembers much about the specifics of who started it but it didn't take long until the whole world was involved. Cities all over were nuked and most people died.</p>
    <p>When I saw that mushroom cloud I knew my life would never be the same. My old life as an English Teacher in a quiet town is long gone. All that's left now is the bitter pain of memory. But scattered relics of a kinder past remain.</p>
    <p>The nuclear holocaust has changed the world forever. The climate changed and many species went extinct. Billions died in giant famines after the fallout had made tons of land sterile and unsuitable for agriculture. Word powers crumbled one by one and democracy was set aside in the remaining nations until all of the world eventually fell into anarchy. There was no cavalry. There was no micracle to save humanity from its impeding doom.</p>
    <p>Now, most cities and towns are deserted. Most people live in independent communities often united by common values, and some live alone. Society is organically growing back, but on a socle of blood and wrath.</p>
    <p>Not a single day goes without the questionning of the past. Actually, it could be considered more of a questioning of past mistakes.</p>
    <p>I have to get to work now.</p>
    <h5>Friday</h5>
    <p>I've always tried to have a positive perspective on things. Well, if anything, the apocalypse made me realize that what I was the most afraid of was loosing the people who counted to me the most, and being alone.</p>
    <p>I couldn't let the apocalypse change me. But it had changed the face of the world! How could it not have changed me?</p>
    <h4>June</h4>
    <h5>Saturday</h5>
    <p>Yesterday night I went for a night out at the bar. It's pretty much the last building standing here in the old city of Lannion. All around it are ruins.</p>
    <p>For all these years, I taught. I've always assumed it was what I'd be remembered for.</p>
    <p>But what was left of my life? This world was in ruins. It genuinely seemed that it had nothing to offer me anymore.</p>
    <p>Lushful trees, a bright sun shining over fields, houses, roads and villages, by the seashore, all under a clear blue sky. This place... It was a paradise.</p>
    <p>But it all came to an end, thanks to us humans. Now this is nothing but a barren wasteland, full of broken hopes, lost desires and shattered dreams that stretches as far as the eye can see, devoid of life but full of lost souls who wander, barely surviving, only to regret.</p>
    <p>Last night, as I was going to sleep, I looked at the weak, distant lights in the horizon. As I stared into the dark abyss, I couldn't help but feel a mild satisfaction. The dark hue of the night seemed like the border of the universe. There was no moon visible at this particular time. It must had been hidden by the thick green clouds covering the sky.</p>
    <p>Realizing one's insignificance in this huge universe could have been a fear to some people, but to me, it felt comforting and reassuring.</p>
    <p>After lying down on the cold floor of the room, I closed my eyes, and felt the darkness of the night get to me, but I didn't resist, and let myself fall into a deep sleep.</p>
    <p>It was just another night, seldom troubled by the thurd of the wind blowing through the dead trees, by the hillside and through the dry riverbed where the Léguer used to flow.</p>
    <p>When I woke up, I stood up to look out the window. There were no birds singing, no wind blowing, no sun shining accompanying this eve of a new day. It would have seemed that it was still the night, but I knew this was as clear as days could get under the thick clouds of nuclear winter. At least, it gave me space and time to think, plan ahead, and reflect on things. A brief recess from life in a world I don't feel part of anymore.</p>
    <p>I mean, I can't help it that man's vices had made the flower of human accomplishments wither away, but I do miss the world.</p>
    <p>We had come so far... How could things go so wrong! There must be hope.</p>
    <p>Because even though the unprecedented level of self-awareness we've been able to reach didn't prevent us from blowing ourselves up, if there's anything the bombs didn't disintegrate, it may be hope. Hope that, such as a Phoenix bird, humanity would awaken from its ashes, learn from its past mistakes and learn to live again.</p>
    <p>Hope that we would live up to being human again.</p>
    <p>One day.</p>
    <p>Soon. Maybe.</p>
    <h5>Wednesday</h5>
    <p>That was it. Humanity's ultimate fireworks. Mushroom clouds sprinkled over all contients. Cities falling down and chaos for the last day of mankind. At last, the end to it all.</p>
    <p>In a way, it was beautiful and fascinating to watch. Seeing the world burst into flames did make all human accomplishments and potential worthless, but it also meant no school, no work, no responsibilities, no anger, no hate, and no hard feelings. None of those silly concerns of the living would follow me into the grave.</p>
    <p>I remember, we kept listening to the emergency broadcasts until the very end, when every country, upon realizing that there was no hope of destroying the nukes, agreed on a worldwide diffusion of Armstrong's "What a wonderful world", along with a message, written in a blue Comic Sans font over footage of natural landscapes that seemed to come from Voyager's gold disk, reading <q>The world is about to end. Nukes are flying towards every major city, and the subsequent nuclear fallout will decimate the biosphere. We advise you to seek shelter and stay with your relatives. May the survivors rebuild a better world and not commit the same mistakes. Goodbye.</q> It was frightening, but honest, and looking back, I appreciate that. For our last moments, we were as kind to each other as possible. It was truly beautiful.</p>
    <p>The apocalypse was the same for everyone. It leveled out our differences. All the issues of society were gone, as we were all equals in the eyes of death. Yet, some of us survived. Some considered themselves lucky, others considered themselves worthy of divine honor. But it hardly made a difference on the long run.</p>
    <p>I have witnessed death and destruction, lost loved ones.</p>
    <p>I have experienced the worst pain imaginable.</p>
    <p>I have faced the challenges of survival in a broken world, such as finding food, water and shelter.</p>
    <p>I've had to face the loss of culture, family, customs, the whole backbone of my life.</p>
    <p>I've had to live virtually on my own, all by myself in a world altered beyond recognition.</p>
    <p>Yet, I survived. Barely, but I did survive.</p>
    <p>Frankly, I wish I hadn't.</p>
    <h3>Chapter 2: Blank canvas</h3>
    <h4>September</h4>
    <h5>Thursday</h5>
    <p>I provide for myself everyday. However I feel like something is missing. I need a way to feel part of something bigger than me again. I want to help others. I want to contribute.</p>
    <p>And I think I know how.</p>
    <p>I want to rebuild society. A fresh start for humans, with the knowledge of past events and mistakes. A sustainable society that values what's really important, and doesn't give any credit to delusions. A place for everyone. A place centered around compassion, just like us.</p>
    <p>A world that values human rights, democracy, freedom for everyone, environmental sustainability, and, most of all, social and technological enlightenment.</p>
    <p>How am I going to do that? And most importantly, what qualifies me, to be the one doing this?</p>
    <p>I mean, other people must feel the same way as me. So why aren't there utopias all over the place?</p>
    <p>Well, I probably don't have what it takes, nor any of the skills necessary to rebuild society but I don't need to. I only have to find people that do. Except I don't want to be a ruler, let alone some kind of dictator.</p>
    <p>Why aren't there utopias? Well, maybe I'm the first one. Maybe all the others have already given up. I choose not to give up. I choose to have hope and goodwill. I choose to believe that rebuilding society is possible.</p>
    <p>Because we must at least try. At least, it'll give us something to do instead of killing each other over silly concerns.</p>
    <p>A society driven by science, empathy and honesty, that would encourage thoughtful innovation to solve problems.</p>
    <p>About that, there were only two times during which human technology thrived, wars and rivalries.</p>
    <p>During times of crisis we're too busy taking care of our basic needs to innovate.</p>
    <p>During times of plenty we're too constrained by governments, customs and beliefs to innovate meaningfully.</p>
    <p>Before the apocalypse, we had managed to cheat the system with capitalism's indidual-driven innovation, but it had led us to a dangerous path to self-destruction. We can't afford to make that same mistake again, and we won't.</p>
    <p>We must break the cycle of stagnation, and unleash our true power.</p>
    <p><strong>The power of kindness.</strong></p>
</div>