<?php
require_once 'fragment.php';
$f = new Fragment(__FILE__, 'en') ?>
<div>
    <p><?= $f->def('anno2070') ?> islands are not randomly generated. There's a set of islands defined in the game's files. They are rotated and placed randomly to create an illusion of randomness, but all maps actually have the same islands.</p>
    <p>So I reproduced them in <?= $f->def('anno-designer') ?>.</p>
</div>
<article>
    <h3>Possible usages</h3>
    <ul class="list">
        <li><p><strong>Making island-wide layouts.</strong> I often use building layouts to optimize space usage, but layouts have a major flaw: they are assumed t</p>o be rectangles. Their space efficiency is based on their bounding box, but islands are not rectangles. They have rather irregular shapes. Which is why one can't solely rely on current building layouts to build efficiently.</li>
        <li><p><strong>Computing optimal island-wide layouts with an algorithm</strong> (really looking forward to that one). It's an NP-hard<?=$f->ref()?> problem, so the solution will require heuristics. I haven't researched it thoroughly yet, but the implementation promises to be an interestign challenge.</p></li>
    </ul>
    <ul class="list">
    <li><p><strong>Black</strong>: blocked tile (Rock, reef, river&hellip;)</p></li>
    <li><p><strong>Yellow</strong>: shore (near rivers and on the coast, some tiles can have roads built on them, but nothing else)</p></li>
    <li><p><strong>Blank</strong>: water or land.</p></li>
    <li><p><strong>Purple</strong>: oddity (oddly-behaving tiles)</p></li>
    </ul>
    <figure class="figure">
        <img src="/portfolio/img/project/island-maps/3_mines_1_river.webp" alt="Island 1 &ndash; 3 mines 1, river slot" width="800" height="571" loading="lazy" title="Island 1 &ndash; 3 mines, 1 emplacement fluival">
        <figcaption>Island 1 &ndash; 3 mines, 1 river slot</figcaption>
    </figure>
    <p>This is the first island I've reproduced. It's among the smallest islands in the game.</p>
    <p><strong>Oddity</strong>: this tile is not buildable, but it still makes a sound when you try to build a road on it.</p>
</article>