<div>
    <p>As a child, my parents introduced me to Val d'Isère, a ski resort located in the Alps. Since then, we go back twice a year, in summer and in winter.</p>
    <figure class="figure">
        <p>(summer/winter photo comparison slider (view from apartment))</p>
        <figcaption>view from our apartment summer/winter</figcaption>
    </figure>
</div>
<article>
    <h3>Winter</h3>
    <div>
        <p>In winter, we mainly ski. The ski area is the largest in Europe, so even after all these years, we haven't been everywhere yet.</p>
        <figure class="figure">
            <p>(foggy chairlift ski photo)</p>
            <figcaption>You can't see anything!</figcaption>
        </figure>
        <p>I went through the <abbr title="French Ski School">ESF</abbr>. However, after getting the Gold Star, I decided not to continue competing because it's not really my state of mind. Being on vacation, I come to ski to relax and stay calm. However, that doesn't mean I don't enjoy taking on certain challenges:</p>
        <p>Every year we try to make the most of it, because due to global warming, the glaciers are retreating and the snowpack is getting thinner every year.</p>
        <p>Sooner or later, skiing will disappear. Val d'Isère, one of the highest resorts in France, will be the last bastion of this legendary sport. At least until global warming reaches it too.</p>
        <p>It's not that bad, there will always be summer activities.</p>
    </div>
</article>
<article>
    <h3>Summer</h3>
    <div>
        <p>In the summer, we mainly go hiking. There are a lot of trails accessible to pedestrians in the area. However, the best views are not always found on the most frequented paths:</p>
        <figure class="figure">
            <p>(pissaillas glacier)</p>
            <figcaption>We climbed up to the Pissaillas glacier from the Col de l'Iseran. We were alone and the landscape was simply wonderful.</figcaption>
        </figure>
    </div>
</article>