<?php
require_once 'fragment.php';
$f = start('fr'); ?>
<div class="cols">
    <p><?= $f->def('c') ?> est le premier langage de programmation que j'ai appris, en <?= $f->year(2017) ?>. Cependant j'ai récemment commencé à apprendre le <?= $f->def('zig') ?>. <?= $f->def('zig') ?> est similaire au <?= $f->def('c') ?> dans ses fondements. C'est un langage de bas niveau, destiné à la programmation système et à l'interaction avec le matériel. Et je suis un grand fan&nbsp;! J'ai implémenté <?= $f->a('un clone de la commande ' . $f->code('test') . ' GNU', 'project/ztest.html') ?> pour me familiariser avec celui-ci. Ce langage résout de nombreux problèmes et limitations du <?= $f->def('c') ?>.</p>
</div>
<article id="generics">
    <h3>Génériques</h3>
    <div class="cols">
        <p>Les génériques ont toujours été difficiles à faire en <?= $f->def('c') ?>. Il y a plusieurs approches&nbsp;: pointeurs sur vide, macros, passer la taille du type. Mais il y a très peu de garanties d'exactitude et la syntaxe est pénible.</p>
        <figure class="figure">
            <?= $f->codeblock(<<<CODE
#include <stddef.h>
#include <stdlib.h>
#include <string.h>

#define vector_MIN_CAP 32

#define vector_struct(T) \
  typedef struct T##_vector { \
    T *buf; \
    size_t capacity; \
    size_t size; \
  } T##_vector;

#define vector_init(T) \
  void T##_vector_init(T##_vector *vec) { \
    vec->capacity = vector_MIN_CAP; \
    vec->buf = malloc(sizeof(T) * vec->capacity); \
    vec->size = 0; \
  }

#define vector_get(T) \
  void *T##_vector_get(T##_vector *vec, size_t idx) { return vec->buf + idx; }

#define vector_set(T) \
  void T##_vector_set(T##_vector *vec, size_t idx, T data) { \
    vec->buf[idx] = data; \
  }

#define vector_push(T) \
  void T##_vector_push(T##_vector *vec, T data) { \
    if (vec->size == vec->capacity) { \
      vec->capacity *= 2; \
      vec->buf = realloc(vec->buf, sizeof(T) * vec->capacity); \
    } \
    T##_vector_set(vec, vec->size++, data); \
  }

#define vector(T) \
  vector_struct(T); \
  vector_init(T) vector_get(T) vector_set(T) vector_push(T)
CODE) ?>
            <figcaption>Impleméntation d'un vecteur générique utilisant les macros en <?= $f->def('c') ?><?= $f->ref() ?>. Comme vous pouvez le voir, le code est embrouillé et fragile. L'utilisation serait inutilement verbeuse et pénible.</figcaption>
        </figure>
        <p>En <?= $f->def('zig') ?>, les génériques sont simples comme bonjour. Vous pouvez passer des arguments de types aux fonctions comme citoyens de première classe. Vous pouvez aussi stocker des types dans des constantes.</p>
        <p>Et pour les structures de données génériques&nbsp;? Définissez simplement une fonction générique qui définit la structure localement en utilisant les arguments de type et qui retourne une instance de celle-ci.</p>
        <figure class="figure">
            <?= $f->codeblock(<<<CODE
pub fn Binary(comptime T: type) type {
    return struct {
        left: T,
        right: T,
    };
}
CODE) ?>
            <figcaption>Exemple de code <?= $f->def('zig') ?> pour une structure de données générique (une expression binaire pour un analyseur)</figcaption>
        </figure>
    </div>
</article>
<article id="explicit-and-exhaustive-error-handling">
    <h3>Gestion des erreurs explicite et exhaustive</h3>
    <div class="cols">
        <figure class="figure">
            <?= $f->codeblock('printf("Hello world\n");') ?>
            <figcaption>Ce code peut échouer. <strong>L'erreur est ignorée.</strong></figcaption>
        </figure>
        <figure class="figure">
            <?= $f->codeblock(<<<CODE
const stdout = std.io.getStdOut().writer();
try stdout.print("Hello world\n");
CODE) ?>
            <figcaption>Ce code peut aussi échouer. Mais le <?= $f->code('try') ?> indique qu'en cas d'erreur, celle-ci est <strong>retournée</strong>. Si nous sommes dans la fonction <?= $f->code('main') ?>, cela fera planter le programme.</figcaption>
        </figure>
        <p>Selon la <cite>page de manuel de <?= $f->code('printf') ?></cite>, <q>si une erreur de sortie est rencontrée, une valeur négative est retournée</q>. Cela signifie que pour être correct à 100% et gérer tous les cas d'erreur possibles, nous devons entourer tous les appels à <?= $f->code('printf') ?> (ou toute fonction de la même famille) dans une instruction <?= $f->code('if') ?> et gérer l'erreur de manière appropriée.</p>
        <p>Mais qui fait cela&nbsp;? La valeur de retour de <?= $f->code('printf') ?> est presque toujours ignorée. La raison est que nous ne savons pas quoi faire quand il y a une erreur. Si <?= $f->code('printf') ?> a échoué, quelque chose doit sérieusement clocher sur le système, et le programme va probablement bientôt planter. Peut-être que nous sommes à court de mémoire ou qu'une panique de noyau est en train d'avoir lieu. Quitter parait être bon un choix&nbsp;; mais ce n'est pas comportement exprimé quand vous ignorez implicitement la valeur de retour de <?= $f->code('printf') ?>&nbsp;; au lieu de ça, l'erreur est ignorée et le programme continue, comme si rien ne s'était passé.</p>
        <p>Le modèle de gestion d'erreur explicite de <?= $f->def('zig') ?> est un indispensable. Il utilise aussi le modèle des <q>erreurs comme valeurs</q> avec les ensembles d'erreurs. Il y a aussi des invariants au moment de la compilation pour que toutes les erreurs soient gérées.</p>
        <p>L'ignorance n'est plus le comportement par défaut. Ensembles, ascendons et construisons des logiciels plus sûrs.</p>
    </div>
</article>
<article id="explicit-number-sizes">
    <h3>Tailles de nombre explicites</h3>
    <div class="cols">
        <p><?= $f->def('zig') ?> n'a pas de type entier ou en point flottant dont la taille est déterminée par le compilateur et l'architecture que vous utilisez. Plutôt, toutes les tailles de nombre sont indiquées dans le code&nbsp;: <?= $f->code('u32') ?> pour un entier non signé sur 32 bits, par exemple.</p>
        <p>Je trouvais cela fastidieux au début&nbsp;; mais ça devient logique en y réfléchissant un peu&nbsp;: <strong>vous</strong> donnez à la variable sa valeur, donc <strong>vous</strong> devriez décider de sa taille, car elle détermine l'intervalle des valeurs qu'elle peut contenir.</p>
        <p>Il est possible que cette approche explicite eut prévenu l'explosion de la fusée Ariane 5 causée par un dépassement d'entier<?= $f->ref() ?>.</p>
    </div>
</article>
<article id="defer-the-best-thing-since-sliced-bread">
    <h3><?= $f->code('defer') ?>: la meilleure invention depuis le bouton à quatre trous</h3>
    <div class="cols">
        <p><?= $f->code('defer') ?> est un concept certes simple mais qui résout beaucoup de problèmes. Il regroupe les instructions logiquement ou sémantiquement liées dans le code, sans pour autant altérer leur ordre d'exécution.</p>
        <p>Son objectif initial est de simplifier les allocations mémoire, mais il peut être utilisé pour d'autres choses. <?= $f->code('defer') ?> aide à s'assurer à réduire la différence entre la portée et la durée de vie des objets. Au lieu d'avoir à se rapeller de manuellement désallouer la ressource à a fin du bloc, vous pouvez ajouter une instruction <?= $f->code('defer') ?> juste sous l'instruction qui alloue la ressource.</p>
        <figure class="figure">
            <?= $f->codeblock(<<<CODE
var i: u8 = 1;
while (i < 100) {
    defer i++;

    // la valeur de i n'a pas changé
    // Instructions supplémentaires
    // ...
}
CODE) ?>
            <figcaption>Un autre utilisation de <?= $f->code('defer') ?> pour incrémenter un variant de boucle. L'incrémentation est faite au début de la boucle, près de la condition et de la déclaration du variant. Or elle n'est réellement exécutée qu'à la fin du bloc de la boucle.</figcaption>
        </figure>
    </div>
</article>
<article id="a-richer-standard-library">
    <h3>Une bibliothèque standard plus riche</h3>
    <div class="cols">
        <p>La blibliothèque standard du <?= $f->def('c') ?> est plutôt rudimentaire. On a souvent besoin de télécharger une bibliothèque STB<?= $f->ref() ?> quand on a besoin d'un allocateur en arène ou d'une table de hachage.</p>
        <p>On peut aussi apprendre à implémenter ces structures de données et algorithmes soi-même, ce qui explique pourquoi je pense qu'apprendre le <?= $f->def('c') ?> comme premier langage de programmation m'a aidé à devenir un meilleur programmeur.</p>
        <p><?= $f->def('zig') ?> résout ce problème en ayant une bibliothèque standard plus riche. Cette approche n'est pas unique à <?= $f->def('zig') ?>. Des langages similaires comme <?= $f->def('go') ?> ou <?= $f->def('rust') ?> ont eux aussi des bibliothèques standard riches.</p>
    </div>
</article>
<article id="a-standard-build-system">
    <h3>Un système de génération standardisé</h3>
    <div class="cols">
        <p><?= $f->def('c') ?> n'a pas de système de génération <q>officiel</q>&nbsp;; à la place, on a des systèmes de génération tiers comme <?= $f->def('make') ?> or <?= $f->def('cmake') ?>.</p>
        <p>Le système de génération de <?= $f->def('zig') ?> est distribué avec le compilateur. Celui-ci utilise une approche déclarative. Ce que j'apprécie particulièrement est qu'il n'introduit pas de nouveau langage. À la place, les commandes de génération sont exprimées en <?= $f->def('zig') ?>.</p>
    </div>
</article>
<article id="namespaces">
    <h3>Espaces de noms</h3>
    <div class="cols">
        <p>Ah, la joie de préfixer chaque symbole dans un programme <?= $f->def('c') ?> pour éviter les conflits de nom avec les utilisateurs de votre bibliothèque&nbsp;!</p>
        <p>Les espaces de noms sont devenus le standard incontournable des langages de programmation modernes. C'est très utile et idiomatique de manipuler une blibliothèque ou un modules comme ce qu'il est&nbsp;: un sac de noms.</p>
    </div>
</article>
<article id="encapsulation">
    <h3>Encapsulation</h3>
    <div class="cols">
        <p>Plus de besoin de préfixer les fonctions internes avec un underscore&nbsp;! <?= $f->code('pub') ?> est tout ce dont vous avez besoin.</p>
        <p>Plus sérieusement, l'encapsulation n'existe pas en <?= $f->def('c') ?>. Bien que la convention de <q>si ça commence par un underscore, ne pas y toucher</q> s'est répandue depuis un moment maintenant, c'est toujours plus sûr quand le langage impose l'invariant de <q>on ne peut pas accéder à ceci en dehors de ce module / cette structure</q>.</p>
        <p>En <?= $f->def('c') ?>, il faut être créatif. Pour éviter tout conflit de nom avec des internes de d'autres bibliothèques que l'utilisateur pourrait implémenter, votre préfixe interne ne devrait pas seulement commencer par un underscore, mais aussi contenir une suite de caractères unique (espérons-le). De plus, l'underscore ne devrait pas être suivi par une lettre majuscule, sauf si vous voulez violer le standard et vous exposer à des conflits de nom avec le compilateur ou des internes de la bibliothèque standard.</p>
        <p>Par exemple, <?= $f->a("Cori", 'project/cori.html') ?> utilise le préfixe <?= $f->code('_cori_') ?> pour les fonctions, macros, structures, alias de type, etc. internes.</p>
        <p>En <?= $f->def('zig') ?>, vous n'avez pas besoin de toute cette folie. Privé est par défaut. Exportes des fonctions, des structres et des méthodes avec le mot-clé <?= $f->code('pub') ?>.</p>
    </div>
</article>
<article id="if-it-compiles-it-works">
    <h3><q>Si ça compile, ça marche</q></h3>
    <div class="cols">
        <p><?= $f->def('zig') ?> est beaucoup, beaucoup plus près de l'idéal de <q>si ça compile, ça marche</q> que le <?= $f->def('c') ?>.</p>
        <p>Certes, tout ce qui peut être fait en <?= $f->def('zig') ?> peut aussi être fait en <?= $f->def('c') ?>, mais les invariants et les restrictions que <?= $f->def('zig') ?> impose sont des choses dont vous n'aurez pas à vous rappeler, comme quand vous codez en <?= $f->def('c') ?>.</p>
        <p>Pour moi, c'est l'objectif de tout langage de programmation&nbsp;: fournir une syntaxe expressive de sorte à donner autant de guaranties de conformité et de justesse que possible au moment de la compilation.</p>
        <p>En somme, je pense que le langage <?= $f->def('c') ?> a suivi son cours. BIen sûr, il sera toujours utilisé, car énormément de programmes sont écrits en <?= $f->def('c') ?>, et il serait ridicule d'attendre que tout soit réécrit en <?= $f->def('rust') ?> ou <?= $f->def('zig') ?>. Cependant, je ne m'attendrais pas à le voir utilisé pour tout nouveau projet <q><?= $f->term('en', 'greenfield') ?></q>.</p>
        <p>Néanmoins, je pense que le <?= $f->def('c') ?> est un très bon langage à apprendre. Il vous force à quitter votre zone de confort d'abstractions et à faire face au réel défi d'implementer des choses que nous utilisons tous les jours en tant que programmeurs, comme les vecteurs ou les tables de hachage.</p>
    </div>
</article>
<article id="conclusion">
    <h3>Conclusion</h3>
    <div class="cols">
        <p>En conclusion, le paysage de la programmation est en constante évolution et bien que <?= $f->def('c') ?> ait été un langage fondamental pendant des décennies, l'émergence de <?= $f->def('zig') ?> présente une alternative prometteuse. En tant que programmeur, mon parcours a commencé avec <?= $f->def('c') ?>, un langage qui a non seulement façonné ma compréhension des concepts fondamentaux de la programmation, mais a également joué un rôle déterminant dans l'histoire de la programmation informatique. Sa simplicité, son efficacité et sa portabilité en ont fait un langage de choix pour la programmation système depuis sa création en <?= $f->year(1972) ?>.</p>
        <p>Cependant, alors que nous nous dirigeons vers un avenir où la sécurité, les performances et la productivité des développeurs sont primordiales, <?= $f->def('zig') ?> se démarque comme un choix solide. La philosophie de conception de <?= $f->def('zig') ?>, qui met l'accent sur le maintien de la simplicité et du contrôle de bas niveau de <?= $f->def('c') ?> tout en offrant des fonctionnalités modernes pour assurer la correction à la compilation et appliquer des invariants, en fait un choix attrayant.</p>
        <p>Bien que <?= $f->def('c') ?> ne soit peut-être pas aussi tendance ou riche en fonctionnalités que les langages plus récents, son influence et son importance ne peuvent être sous-estimées. Cependant, la marée semble tourner avec des langages comme <?= $f->def('zig') ?>, qui offrent le meilleur des deux mondes &mdash; la puissance de <?= $f->def('c') ?> et la sécurité des langages modernes. Alors que nous continuons à rechercher un code meilleur et plus sûr, je m'attends à ce que <?= $f->def('zig') ?> remplace progressivement <?= $f->def('c') ?> dans de nombreux domaines, offrant une nouvelle norme pour les langages de programmation système.</p>
        <p>Au final, le choix entre <?= $f->def('c') ?> et <?= $f->def('zig') ?> dépendra des besoins spécifiques du projet et de la familiarité du développeur. Cependant, une chose est claire&nbsp;: <?= $f->def('zig') ?> est un langage à surveiller de près, et je suis impatient de voir comment il façonnera l'avenir de la programmation.</p>
    </div>
</article>