<?php
require_once 'fragment.php';
$f = start('fr') ?>
<div>
    <p>L'objectif de ce projet était de créer un générateur de documents <?= $f->def('php') ?> grâce à la conteneurisation Docker et en utilisant également <?= $f->def('php') ?>, le scripting <?= $f->def('bash') ?> etc. Nous étions en groupes de 4. De mon côté, je me suis occupé d'écrire un parser Markdown en <?= $f->def('php') ?>. Nos professeurs ont été malins&nbsp;: ils ont modifé la syntaxe Markdown pour pas que l'on puisse simplement copier un parser d'Internet.</p>
</div>