<?php
require_once 'fragment.php';
$f = new Fragment(__FILE__, 'en')
?>
I attended <?=$f->a('Lycée Saint-Joseph-Bossuet', 'https://www.saintjosephlannion.fr/')?> in Lannion. I followed the general stream. In the first year, I followed the specializations <?=$f->def('spe-math')?>, <?=$f->def('nsi')?> and <?=$f->def('amc')?>. In the final year, I decided to abandon mathematics in favor of my two other specializations. In passed my baccalaureate with honors.